#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python
##!/usr/bin/python

import matplotlib
matplotlib.use('QT4Agg') # has to be imported before the next lines
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np

import analysis as ana

def main():
    path="/hiskp2/jost/correlationfunctions/liuming_pion/D15_all/"
    filelist = ["pi_corr_p%d" % (x) for x in xrange(4)]
    filelist += ["pipi_pipi_A1_corr_TP0_%02d" % (x) for x in [00, 11, 22]]
    #filelist += ["pipi_pipi_A1_corr_TP1_%02d" % (x) for x in [00, 11]]
    #filelist += ["pipi_pipi_A1_corr_TP2_%02d" % (x) for x in [00, 11]]
    #filelist += ["pipi_pipi_A1_corr_TP3_%02d" % (x) for x in [00, 11]]
    suffix = ".dat"
    T=96
    tlist = np.linspace(0., float(T), float(T), endpoint=False)
    fit = lambda p, t: p[0]*np.cosh(p[1]*(int(T/2)-t))
    label = ["single pion, D15", "time", "C(t)", "data", ""]

    for f in filelist:
        print(f)
        data = ana.read_data_ascii("".join((path, f, suffix)))
        #print(data.shape)
        mdata, ddata = ana.calc_error(data)
        mdata = np.atleast_2d(mdata)
        ddata = np.atleast_2d(ddata)
        #print(mdata.shape, ddata.shape)
        res, chi2, p = ana.fitting(fit, tlist[10:-10], data[:,10:-10], [1., 0.07], verbose=True)
        pfit = PdfPages("./plots/%s.pdf" % f)
        label[3] = "fit %d:%d" % (tlist[10], tlist[-11])
        #print(mdata[0].shape, ddata[0].shape, len(tlist))
        ana.corr_fct_with_fit(tlist, mdata[0], ddata[0], fit, res[0], [1,T], label, pfit, True)
        for i in xrange(data.shape[0]):
            if (np.abs( data[i,1] - mdata[0,1] ) > 3. * ddata[0,1]) :
                print("large deviation on data set %d" % i)
            ana.corr_fct_with_fit(tlist, data[i], ddata[0], fit, res[0], [1,T], label, pfit, True)
        pfit.close()
    pass

# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("Keyboard Interrupt")
