#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python

import numpy as np

def main():
    inputlist = [x for x in range(0,1500,80)]
    path = "/hiskp2/jost/code/analysis-code/data/I2/globalfit/"
    res = []
    chi2 = []
    for i in inputlist:
        try:
            fname = "".join((path, "gfitdata_%d.npz"%i))
            f = np.load(fname)
            res.append(f['res'])
            chi2.append(np.atleast_2d(f['chi2']))
            print(res[-1].shape)
            print(chi2[-1].shape)
        except IOError:
            print("could not open %s" % fname)
    print(type(res[0]))
    tmpres = res[0]
    for r in res[1:]:
        tmpres = np.vstack((tmpres, r))
    print(tmpres.shape)
    tmpchi2 = chi2[0]
    for r in chi2[1:]:
        tmpchi2 = np.hstack((tmpchi2, r))
    print(tmpchi2.shape)
    fname = "".join((path, "gfitdata.npz"))
    np.savez(fname, res=tmpres, chi2=tmpchi2[0])


# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
