#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python

import os
import sys
import numpy as np
import ConfigParser

import analysis2 as ana

def main():
    if len(sys.argv) < 2:
        ens = ana.LatticeEnsemble.parse("A40.24.ini")
    else:
        ens = ana.LatticeEnsemble.parse(sys.argv[1])

    # read settings
    readdata = False
    preparedata = False
    readfit = False
    plotdata = True
    exrm = True
    d2 = 0

    # get data from input file
    prefix = ens.get_data("path")
    lat = ens.name()
    nboot = int(ens.get_data("nboot"))
    ddir = "/".join((ens.get_data("datadir"), lat))
    pdir = "/".join((ens.get_data("plotdir"), lat))
    L = ens.L()
    quarks = ens.get_data("quarks")
    Ti = ens.get_data("ti")
    Tf = ens.get_data("tf")
    dti = ens.get_data("dti")
    dtf = ens.get_data("dtf")
    dt = ens.get_data("dt")
    addT = np.ones((nboot,)) * ens.T()
    try:
        debug = ens.get_data("debug")
    except KeyError:
        debug = 0
    try:
        irrep = ens.get_data("irrep")
    except KeyError:
        irrep = "A1"
    if irrep == "A1":
        suffix = "TP%d.npz" % d2
    else:
        suffix = "TP%d_%s.npz" % (d2, irrep)
    masses = ens.get_data("strange_masses")
    smassdirs = ["strange_%s" % (m.ljust(4, "0")) for m in masses]

    # generate file names
    files = [["%s/%s/eta_%s%s_corr_p0.dat" % (prefix, s, i, j) for i in quarks for j in quarks] for s in smassdirs ]
    datadir = [os.path.join(ddir, s) for s in smassdirs]
    plotdir = [os.path.join(pdir, s) for s in smassdirs]
    #print(files)
    #print(datadir)
    #print(plotdir)

    for d, p, fil in zip(datadir, plotdir, files):
        print("data dir %s\nplot dir %s" % (d, p))
        # read data
        if exrm:
            if readdata == False:
                corr = ana.Correlators.read("%s/eta_gevp_rm_%s" % (d, suffix))
                # data is already bootstrapped
                corr.shift(1)
                corr.gevp(2)
                corr.save("%s/corr_eta_rm_%s" % (d, suffix))
            else:
                corr = ana.Correlators.read("%s/corr_eta_rm_%s" % (d, suffix))
        else:
            if readdata == False:
                corr = ana.Correlators.read("%s/eta_gevp_%s" % (d, suffix))
                # data is already bootstrapped
                corr.shift(1)
                corr.gevp(2)
                corr.save("%s/corr_eta_%s" % (d, suffix))
            else:
                corr = ana.Correlators.read("%s/corr_eta_%s" % (d, suffix))

        # fit the data
        fitter = ana.LatticeFit(5, dt_i=dti, dt_f=dtf, dt=dt, correlated=True, xshift=0.5)
        if readfit == False:
            print("fit data")
            fitranges = [Ti, Tf]
            #fitranges = [[Ti, Ti+5, Tf-5, Tf],] + [[Ti, Ti+5, Tf-5, Tf],]
            #print(fitranges)
            fitres = fitter.fit(None, corr, fitranges, corrid="E", add=addT, lint=False)
            if exrm:
                fitres.save("%s/fit_eta_rm_%s" % (d, suffix))
            else:
                fitres.save("%s/fit_eta_%s" % (d, suffix))
        else:
            print("read fitted data")
            if exrm:
                fitres = ana.FitResult.read("%s/fit_eta_rm_%s" % (d, suffix))
            else:
                fitres = ana.FitResult.read("%s/fit_eta_%s" % (d, suffix))
        fitres.print_data(0)
        fitres.print_data(1)
        fitres.print_details()

        # plot the result
        if plotdata:
            print("plotting")
            if exrm:
                plotter = ana.LatticePlot("%s/fit_eta_rm_%s" % (p, suffix.replace(".npz", ".pdf")))
            else:
                plotter = ana.LatticePlot("%s/fit_eta_%s" % (p, suffix.replace(".npz", ".pdf")))
            plotter.set_env(ylog=True)
            label = ["eta energy", "t", "C(t)", "E$_\eta$"]
            plotter.plot(corr, label, fitres, fitter, add=addT, xshift=0.5)
            if d2 == 0:
                if exrm:
                    plotter.new_file("%s/eff_mass_eta_rm_%s" % (p, suffix.replace(".npz", ".pdf")))
                else:
                    plotter.new_file("%s/eff_mass_eta_%s" % (p, suffix.replace(".npz", ".pdf")))
                label = ["eta correlators", "t", "C(t)", "E$_{\eta}$"]
                plotter.set_env(ylog=False)
                plotter.plot(corr, label)
                plotter.set_env(ylog=True)
                plotter.plot(corr, label)
                plotter.set_env(ylog=False, ylim=[0., 1.])
                corr.mass()
                label = ["eta effective mass", "t", "m$_{eff}$(t)", "m$_{\eta}$"]
                plotter.plot(corr, label)
            if exrm:
                plotter.new_file("%s/hist_fit_eta_rm_%s" % (p, suffix.replace(".npz", ".pdf")))
            else:
                plotter.new_file("%s/hist_fit_eta_%s" % (p, suffix.replace(".npz", ".pdf")))
            label = ["eta energy", "E$_{\eta}$/a", "E$_{\eta}$"]
            plotter.histogram(fitres, label, par=1)
            del plotter
        del corr
        del fitres

# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
