#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python
##!/usr/bin/python2

import sys
import numpy as np

import analysis2 as ana

def main():
    # parse the input file
    if len(sys.argv) < 2:
        ens = ana.LatticeEnsemble.parse("A40.24.ini")
    else:
        ens = ana.LatticeEnsemble.parse(sys.argv[1])

    # read settings
    readdata = True
    readfit = False
    plotdata = True

    # get data from input file
    prefix = ens.get_data("path")
    lat = ens.name()
    nboot = ens.get_data("nboot")
    datadir = "/".join((ens.get_data("datadir"), lat))
    plotdir = "/".join((ens.get_data("plotdir"), lat))
    T = ens.T()
    T2 = ens.T2()
    pmax = ens.get_data("pmax")
    Ti = ens.get_data("ti")
    Tf = ens.get_data("tf")
    dti = ens.get_data("dti")
    dtf = ens.get_data("dtf")
    dt = ens.get_data("dt")
    try:
        debug = ens.get_data("debug")
    except KeyError:
        debug = 0
    try:
        hasvev = ens.get_data("hasvev")
    except KeyError:
        hasvev = False

    #files = ["%s/pi_corr_p%d.dat" % (prefix, d) for d in range(pmax)]
    files = ["%s/pipi_I0_corr%d_33.dat" % (prefix, d) for d in [0,2]]
    addT = np.ones((nboot,)) * T

    print("read data")
    xshift = 0.
    if hasvev:
        xshift = 0.5
    if readdata == False:
        corr = ana.Correlators(files, matrix=False)
        # FOR TESTING
        cnfgs = [x for x in range(714, 2751, 2)]
        print(len(cnfgs))
        corr = ana.Correlators.create(-corr.data[:,:,0] + 2*corr.data[:,:,1])
        print(corr.shape)
        corr.sym_and_boot(nboot)
        if hasvev:
            corr.shift(dt=1)
        #corr.save("%s/corr_pi.npz" % (datadir))
        corr.save("%s/corr_pi_liuming.npz" % (datadir))
    else:
        #corr = ana.Correlators.read("%s/corr_pi.npz" % (datadir))
        corr = ana.Correlators.read("%s/corr_pi_liuming.npz" % (datadir))

    print("fitting")
    fitter = ana.LatticeFit(5, dt_i=dti, dt_f=dtf, dt=dt, correlated=True,
        xshift=xshift)
    #fitter = ana.LatticeFit(0, dt_i=dti, dt_f=dtf, dt=dt, correlated=False)
    if readfit == False:
        #fitres = fitter.fit(None, corr, [10, 40], corrid="epi", add=addT)
        #fitres = fitter.fit(None, corr, [Ti, T], corrid="epi", add=addT)
        #fitres = fitter.fit(None, corr, [Ti, Tf], corrid="epi", add=addT)
        fitres = fitter.fit(None, corr, [[Ti, Ti+3, Tf-3, Tf]], corrid="epi", add=addT, lint=True)
        #fitres.save("%s/fit_pi.npz" % (datadir))
        fitres.save("%s/fit_pi_liuming.npz" % (datadir))
    else:
        #fitres = ana.FitResult.read("%s/fit_pi.npz" % (datadir))
        fitres = ana.FitResult.read("%s/fit_pi_liuming.npz" % (datadir))
    #print(corr.data[0][:,0])
    #fitres.print_data(0)
    fitres.print_data(1)
    fitres.print_details()

    # plot the result
    if plotdata:
        plotter = ana.LatticePlot("%s/fit_pi.pdf" % (plotdir))
        plotter.set_env(ylog=True)
        label = ["single pion energy", "t", "C(t)", "E$_{\pi}$"]
        plotter.plot(corr, label, fitres, fitter, add=addT, xshift=xshift, ploterror=True)
        plotter.new_file("%s/hist_fit_pi.pdf" % (plotdir))
        #plotter = ana.LatticePlot("%s/hist_fit_pi.pdf" % (plotdir))
        label = ["single pion energy", "E$_\pi$/a", "E$_\pi$"]
        plotter.histogram(fitres, label, par=1)
        plotter.new_file("%s/eff_mass_pi.pdf" % (plotdir))
        plotter.set_env(ylog=False)
        #plotter = ana.LatticePlot("%s/eff_mass_pi.pdf" % (plotdir))
        corr.mass()
        label = ["single pion effective mass", "m$_{\pi,eff}$/a", "m$_\pi$", ""]
        plotter.plot(corr, label)
        del plotter

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
