#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python
##!/usr/bin/python2

import sys
import numpy as np
import matplotlib
matplotlib.use('Agg') # has to be imported before the next lines
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

import analysis2 as ana

def main():
    # parse the input file
    if len(sys.argv) < 2:
        ens = ana.LatticeEnsemble.parse("A40.24.ini")
    else:
        ens = ana.LatticeEnsemble.parse(sys.argv[1])

    # read settings
    readdata = True
    preparedata = False
    readfit = True
    plotdata = False

    # get data from input file
    prefix = ens.get_data("path")
    lat = ens.name()
    nboot = int(ens.get_data("nboot"))
    gmax = int(ens.get_data("gmax"))
    datadir = "/".join((ens.get_data("datadir"), lat))
    plotdir = "/".join((ens.get_data("plotdir"), lat))
    d2 = ens.get_data("d2")
    try:
        debug = ens.get_data("debug")
    except KeyError:
        debug = 0
    T2 = ens.T2()
    L = ens.L()
    Ti = ens.get_data("ti")
    Tf = ens.get_data("tf")
    dti = ens.get_data("dti")
    dtf = ens.get_data("dtf")
    dt = ens.get_data("dt")

    files = ["%s/pipi_pipi_A1_corr_TP%d_%d%d.dat" % (prefix, d2, i, j) for i in range(gmax) for j in range(gmax)]
    addT2 = np.ones((nboot,)) * T2
    addT = np.ones((nboot,)) * ens.T()

    # read pion data
    pi = ana.Correlators.read("%s/corr_pi.npy" % (datadir))
    pifit = ana.FitResult.read("%s/fit_pi.npz" % (datadir))

    print("read data")
    if readdata == False:
        corr = ana.Correlators(files)
        corr.sym_and_boot(nboot)
        corr.save("%s/corr_pipi_raw_TP%d.npy" % (datadir, d2))
    else:
        corr = ana.Correlators.read("%s/corr_pipi_raw_TP%d.npy" % (datadir, d2))
    if preparedata:
        if d2 != 0:
            # get m_pi for fitrange
            mpi = pifit.data[0][:,1]
            corr.shift(1, mass=mpi, d2=d2, L=L)
        else:
            corr.shift(1)
        corr.gevp(1)
        corr.save("%s/corr_pipi_TP%d.npy" % (datadir, d2))
        if d2 != 0:
            ratio = corr.ratio(pi, 1, mass=mpi, d2=d2, useall=False, L=L)
        else:
            ratio = corr.ratio(pi, 1, useall=False, L=L)
        ratio.save("%s/ratio_pipi_TP%d.npy" % (datadir, d2))
        orig = ana.Correlators.read("%s/corr_pipi_raw_TP%d.npy" % (datadir, d2))
    else:
        orig = ana.Correlators.read("%s/corr_pipi_raw_TP%d.npy" % (datadir, d2))
        corr = ana.Correlators.read("%s/corr_pipi_TP%d.npy" % (datadir, d2))
        ratio = ana.Correlators.read("%s/ratio_pipi_TP%d.npy" % (datadir, d2))
    orig.shift(1)
    for t in range(ratio.data.shape[1]):
        print("%d %.5e %.5e %.5e %.5e %.5e" % (t, pi.data[0,t,0], orig.data[0,t,0,0], corr.data[0,t,0], ratio.data[0,t,0], corr.data[0,t,0]/orig.data[0,t,0,0]))
    plotter = ana.LatticePlot("%s/corrs_TP%d.pdf" % (plotdir, d2))
    plotter.set_env(ylog=True)
    label = ["two pion energy", "t", "C(t)", "E$_{\pi\pi}$"]
    plotter.plot(corr, label)
    label = ["orig. two pion energy", "t", "C(t)", "E$_{\pi\pi}$"]
    plotter.plot(orig, label)
    plotter.set_env(ylog=False)
    #label = ["rel. error of two pion energy", "t", "$\delta$ C(t)/C(t)", "rel. error"]
    #plotter._genplot_single(corr, label, rel=True)
    #plotter.set_env(ylog=False)
    label = ["ratio", "t", "R(t)", "$\delta$E$_{\pi\pi}$"]
    plotter.plot(ratio, label)
    #plotter.set_env(ylog=True)
    #label = ["ratio, logplot", "t", "log(R(t))", "$\delta$E$_{\pi\pi}$"]
    #plotter.plot(ratio, label)
    #plotter.set_env(ylog=False)
    #label = ["rel. error of ratio", "t", "$\delta$ R(t)/R(t)", "rel. error"]
    #plotter._genplot_single(ratio, label, rel=True)
    del plotter

    print("fitting")
    fitter = ana.LatticeFit(1, dt_i=dti, dt_f=dtf, dt=dt, correlated=True, xshift=0.5)
    #start = [1.088295, 0.4648782]
    if readfit == False:
        #fitranges = [Ti,Tf]
        if L < 25:
            fitranges = [[11,15,18,23],] + [[11,13,19,20],]*(gmax-1)
        elif L < 33:
            fitranges = [[11,15,24,30],] + [[11,13,19,20],]*(gmax-1)
        else:
            fitranges = [[10,20,28,35],] + [[10,12,19,20],]*(gmax-1)
            #fitranges = [[15,27,40,47],] + [[10,12,19,20],]*(gmax-1)
        #print(fitranges)
        fitres = fitter.fit(None, ratio, fitranges, corrid="E", oldfit=pifit,
            oldfitpar=1, useall=False, add=addT, lint=True)
        fitres.save("%s/fit_pipi_ratio_TP%d.npz" % (datadir, d2))
    else:
        fitres = ana.FitResult.read("%s/fit_pipi_ratio_TP%d.npz" % (datadir, d2))
    fitres.print_data(0)
    fitres.print_data(1)
    #fitres.print_details()

    # plot the result
    if plotdata:
        print("plotting")
        plotter = ana.LatticePlot("%s/fit_pipi_ratio_TP%d.pdf" % (plotdir, d2))
        plotter.set_env(ylog=True)
        label = ["ratio fit", "t", "R(t)", "dE"]
        plotter.plot(ratio, label, fitres, fitter, oldfit=pifit, oldfitpar=1,
            add=addT, xshift=0.5)
        plotter.new_file("%s/hist_fit_pipi_ratio_TP%d.pdf" % (plotdir, d2))
        label = ["ratio hist", "dE$_{\pi\pi}$/a", "dE$_{\pi\pi}$"]
        plotter.histogram(fitres, label, par=1)
        del plotter

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
