#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python
##!/usr/bin/python2

import numpy as np

import analysis2 as ana

def main():
    #prefix = "/home/chris/Work/data/"
    prefix = "/hiskp2/correlators/A40.24_L24_T48_beta190_mul0040_musig150_mudel190_kappa1632700/ev120/liuming/"
    files = ["%s/pi_corr_p%d.dat" % (prefix, d) for d in range(3)]
    nboot = 1500
    datadir = "./data/"

    # prepare the fitting of data
    # 0 is single partivle correlation function
    # 1 is ratio fit
    # 2 is constant fit
    print("prepare fit")
    fitter = ana.LatticeFit(0, True)
    start = [1., 0.3]

    for i, f in enumerate(files):
        print("read data")
        # read data, symmetrize and bootstrap
        corr = ana.Correlators(f)
        corr.sym_and_boot(nboot)
        add = np.ones((1500,)) * corr.data.shape[1]

        print("fitting")
        # do the fitting
        fitres = fitter.fit(start, corr, [8, 14], add=add)

        print("save")
        # save the fit result
        fitres.save("%s/fit_pi_p%d.npz" % (datadir, i))
        fitres.print_data()

if __name__ == '__main__':
    try:
        print("starting")
        main()
    except KeyboardInterrupt:
        pass
