#!/usr/bin/python
################################################################################
#
# Author: Christian Jost (jost@hiskp.uni-bonn.de)
# Date:   Februar 2015
#
# Copyright (C) 2015 Christian Jost
# 
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with tmLQCD. If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
#
# Function: A short analysis of the error dependence on the number of
# configurations.
#
# For informations on input parameters see the description of the function.
#
################################################################################

import matplotlib
matplotlib.use('QT4Agg') # has to be imported before the next lines
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np

import analysis as ana

def main():
  ## definition of some variables
    nbsamples = 100
    T = 96
    T2 = int(T/2)+1
    massfunc = lambda p, t: p

    # get mean correlators for varying number of configs

    nb_cfgs = [30,60,90,120,150,180,210]
    path = "/hiskp2/helmes/B35_nb_cfg_test/"
    name_2pt = path+"data/pi_corr_p0.dat"
    name_4pt = path+"data/pipi_pipi_A1_corr_TP0_00.dat"
    plotpath = path+"plots/"
    # Arrays for different configuration subsets
    # shape is ( nb_subsets, time, dat_type)
    mean_corr_2pt = np.zeros((len(nb_cfgs), T2-2, 2))
    mean_corr_4pt = np.zeros((len(nb_cfgs), T2-2, 2)) 
    for _e in range(0,len(nb_cfgs)):
        _c = nb_cfgs[_e]
        corrs_2pt = ana.read_data_part_ascii(name_2pt,_c)
        corrs_4pt = ana.read_data_part_ascii(name_4pt,_c)

        bsamples_2pt =  ana.sym_and_boot(corrs_2pt,nbsamples)
        bsamples_4pt =  ana.sym_and_boot(corrs_4pt,nbsamples)

        corr_2pt_data, d_2pt_data = ana.calc_error(bsamples_2pt)
        corr_4pt_data, d_4pt_data = ana.calc_error(bsamples_4pt)

        # compute effective masses
        m_eff_2pt, mm_eff_2pt, err_m_eff_2pt = ana.compute_mass(bsamples_2pt) 
        m_eff_4pt, mm_eff_4pt, err_m_eff_4pt = ana.compute_mass(bsamples_4pt) 
        # append stuff to array
        mean_corr_2pt [_e,:, 0] = mm_eff_2pt
        mean_corr_2pt [_e,:, 1] = err_m_eff_2pt
        mean_corr_4pt [_e,:, 0] = mm_eff_4pt
        mean_corr_4pt [_e,:, 1] = err_m_eff_4pt


    # plot mean and stdev

    tlist_corr = np.linspace(0., float(T2-2), float(T2-2), endpoint=False)
    label_2pt = ["rel_error", "time", "dC_2(t)/C_2(t)", "data", "#cfg: "+str(_c)]
    label_4pt = ["rel_error", "time", "dC_4(t)/C_4(t)", "data", "#cfg: "+str(_c)]

    # relative error
    rel_err_2pt = np.divide(mean_corr_2pt[:,:,1], mean_corr_2pt[:,:,0])
    rel_err_4pt = np.divide(mean_corr_4pt[:,:,1], mean_corr_4pt[:,:,0])
    

    pfit = PdfPages("%s%s_plot.pdf" % (plotpath,"rel_err_"))
    ana.corr_fct(tlist_corr, rel_err_2pt, [1,T2], label_2pt, pfit, nb_cfgs)
    ana.corr_fct(tlist_corr, rel_err_4pt, [1,T2], label_4pt, pfit, nb_cfgs)
    pfit.close()
    
    # Noise to signal ratios 210 vs 90 configs
    label_2pt = ["Stat. error growth 2pt", "time", "NSR_hi/NSR_low", "data", "#cfg: "+str(_c)]
    label_4pt = ["Stat. error growth 4pt", "time", "NSR_hi/NSR_low", "data", "#cfg: "+str(_c)]
    nsr_2pt = np.divide(rel_err_2pt[6], rel_err_2pt[0] )
    nsr_4pt = np.divide(rel_err_4pt[6], rel_err_4pt[0] )
    pfit = PdfPages("%s%s_plot.pdf" % (plotpath,"NSR_"))
    print nsr_2pt
    ana.corr_fct(tlist_corr, nsr_2pt, [1,T2], label_2pt, pfit, nb_cfgs)
    ana.corr_fct(tlist_corr, nsr_4pt, [1,T2], label_4pt, pfit, nb_cfgs)
    #ana.corr_fct(tlist_corr, rel_err_4pt, [1,T2], label_4pt, pfit)
    pfit.close()



# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
  try:
    main()
  except KeyboardInterrupt:
    print("Keyboard Interrupt")
