#!/usr/bin/python
################################################################################
#
# Author: Christopher Helmes (helmes@hiskp.uni-bonn.de)
# Date:   Februar 2015
#
# Copyright (C) 2015 Christopher Helmes
# 
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with tmLQCD. If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
#
# Function: Programm to match the strange quark mass with three methods for
#           comparison: linear interpolation, linear fit, quadratic
#           interpolation
#
# For informations on input parameters see the description of the function.
#
################################################################################

import sys
import numpy as np
import matplotlib
matplotlib.use('Agg') # has to be imported before the next lines
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

import analysis2 as ana

def main():
    # read settings
    read_m_a0 = False
    plot_hist = True

    # parse the input file
    if len(sys.argv) < 2:
        ens = ana.LatticeEnsemble.parse("A40.24.ini")
    else:
        ens = ana.LatticeEnsemble.parse(sys.argv[1])

    # get data from input file
    lat = ens.name()
    quark = ens.get_data("quark")
    #datadir = ens.get_data("datadir") 
    datadir = "/hiskp4/helmes/analysis/scattering/pi_k/I_32_blocked//data/D30.48/"
    plotdir = ens.get_data("plotdir") 
    #strange = ens.get_data("strange")
    strange = ['amu_s_115','amu_s_15','amu_s_18']
    

    print(datadir)
    print(plotdir)

    # Read in fitted masses, ranges and weights
    # TODO: Automate this for the number of quark masses
    print("Read fit results for single particle masses")
    m0 = ana.FitResult.read("%s/%s/fit_k_%s.npz" % (datadir, strange[0], lat))
    m0.print_data(par=1)

    print("Read fit results for single particle mass")
    m1 = ana.FitResult.read("%s/%s/fit_k_%s.npz" % (datadir, strange[1], lat))
    m1.print_data(par=1)

    print("Read fit results for single particle mass")
    m2 = ana.FitResult.read("%s/%s/fit_k_%s.npz" % (datadir, strange[2], lat))
    m2.print_data(par=1)
    
    # This should be a Fit Result
    mu_s_match = ana.FitResult.match_qm(m1, m2, m3)

    if plot_match:
      print("plotting")
      plotter = ana.LatticePlot("%s/hist_mk_akk_%s.pdf" % (plotdir, lat))
      label = ["Scattering length", "M$_\k$ a$_\k\k$", "M$_\k$ a$_\k\k$"]
      plotter.histogram(mult_obs, label, 1)
      del plotter

# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
