#!/hadron/knippsch/Enthought/Canopy_64bit/User/bin/python
################################################################################
#
# Author: Christian Jost (jost@hiskp.uni-bonn.de)
# Date:   Februar 2015
#
# Copyright (C) 2015 Christian Jost
# 
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with tmLQCD. If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
#
# Function: A programm to print the results of the Luescher analysis 
#
# For informations on input parameters see the description of the function.
#
################################################################################

import sys
import numpy as np
import matplotlib
matplotlib.use('Agg') # has to be imported before the next lines
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

import analysis2 as ana

def main():

    # parse the input file
    if len(sys.argv) < 2:
        ens = ana.LatticeEnsemble.parse("A40.24.ini")
    else:
        ens = ana.LatticeEnsemble.parse(sys.argv[1])

    # get data from input file
    lat = ens.name()
    latA = ens.get_data("namea")
    latB = ens.get_data("nameb")
    strangeA = ens.get_data("strangea")
    strangeB = ens.get_data("strangeb")
    #quark = ens.get_data("quark")
    datadir = ens.get_data("datadir") 
    plotdir = ens.get_data("plotdir") 
    d2 = ens.get_data("d2")

    print(datadir)
    print(plotdir)
    print("Summary for the A-ensembles")
    Aresults = np.zeros((len(strangeA),len(latA),16))
    for i,s in enumerate(strangeA):
      print(s)
      for j,a in enumerate(latA):
        #print(datadir+a+"/"+s)
        ## single particle fit
        #print("read single particle fit")
        #kcorr = ana.Correlators.read("%s/corr_k_%s.npy" % (datadir, lat))
        kfit = ana.FitResult.read("%s%s/%s/fit_k_%s.npz" % (datadir, a,s, a))
        m = kfit.data_for_plot(1)

        # read ratio
        #print("\n\nread ratio")
        ratiofit = ana.FitResult.read("%s%s/%s/fit_kk_TP%d_%s.npz" % (datadir, a, s, d2, a))
        dE = ratiofit.data_for_plot(1)
        
        # Read in results of scattering length
        #print("Read results for scattering length")
        a0 = ana.FitResult.read("%s%s/%s/scat_len_TP%d_%s.npz" % (datadir, a, s, d2, a))
        a0 = a0.data_for_plot()
        
        # Read m_a0
        mult_obs = ana.FitResult.read("%s%s/%s/mk_akk_%s.npz" % (datadir, a, s, a))
        m_a0 = mult_obs.data_for_plot()
        ens = np.vstack((m,dE,a0,m_a0)).reshape(len(latA)*4)
        Aresults[i,j] = ens
    Aresults = Aresults.reshape((8,16))
    print Aresults
    fmt = " ".join(['%1.4e']*16)
    np.savetxt("kk_scat_b1.90.dat",Aresults, fmt=fmt)
    print("Summary for the B-ensembles")
    for a in latB:
      for s in strangeB:
        print(datadir+a+"/"+s)
        ## single particle fit
        print("read single particle fit")
        #kcorr = ana.Correlators.read("%s/corr_k_%s.npy" % (datadir, lat))
        kfit = ana.FitResult.read("%s%s/%s/fit_k_%s.npz" % (datadir, a,s, a))
        kfit.data_for_plot(1)

        # read ratio
        print("\n\nread ratio")
        ratiofit = ana.FitResult.read("%s%s/%s/fit_kk_TP%d_%s.npz" % (datadir, a, s, d2, a))
        ratiofit.data_for_plot(1)
        
        # Read in results of scattering length
        print("Read results for scattering length")
        a0 = ana.FitResult.read("%s%s/%s/scat_len_TP%d_%s.npz" % (datadir, a, s, d2, a))
        a0.data_for_plot()
        
        # Read m_a0
        mult_obs = ana.FitResult.read("%s%s/%s/mk_akk_%s.npz" % (datadir, a, s, a))
        mult_obs.data_for_plot()
        print("#################################################################################")
# make this script importable, according to the Google Python Style Guide
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass

